export const userdata = [
  {
    login_type: "N",
    social_id: "socialid001",
    first_name: "Arjun",
    last_name: "Mistry",
    email: "arjun001@example.com",
    password: "password123",
    country_code: "+91",
    phone: "9876543210",
    dob: new Date("1990-01-01"),
    gender: "male",
    latitude: 23.0258,
    longitude: 72.5873,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: "192.168.1.1",
    app_version: "1.0.0",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "F",
    social_id: "socialid002",
    first_name: "Riya",
    last_name: "Shah",
    email: "riya002@example.com",
    password: "password456",
    country_code: "+44",
    phone: "7712345678",
    dob: new Date("1985-12-15"),
    gender: "female",
    latitude: 51.5074,
    longitude: 0.1278,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: "172.16.0.2",
    app_version: "1.0.2",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "G",
    social_id: "socialid003",
    first_name: "Karan",
    last_name: "Patel",
    email: "karan003@example.com",
    password: "password789",
    country_code: null,
    phone: null,
    dob: null,
    gender: "male",
    latitude: null,
    longitude: null,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: null,
    app_version: null,
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "A",
    social_id: "socialid004",
    first_name: "Meera",
    last_name: "Desai",
    email: "meera004@example.com",
    password: "password321",
    country_code: "+1",
    phone: "5551234567",
    dob: new Date("1992-07-20"),
    gender: "female",
    latitude: 40.7128,
    longitude: -74.006,
    profile_image: "https://example.com/profiles/meera.jpg",
    last_login: new Date(),
    login_status: true,
    ip: "10.0.0.1",
    app_version: "2.0.0",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "N",
    social_id: "socialid005",
    first_name: "Nikhil",
    last_name: "Joshi",
    email: "nikhil005@example.com",
    password: "password654",
    country_code: "+49",
    phone: "15123456789",
    dob: new Date("1988-05-10"),
    gender: "male",
    latitude: 52.52,
    longitude: 13.405,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: null,
    app_version: null,
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "F",
    social_id: "socialid006",
    first_name: "Sneha",
    last_name: "Gandhi",
    email: "sneha006@example.com",
    password: "password987",
    country_code: "+91",
    phone: "9988776655",
    dob: new Date("1995-11-25"),
    gender: "female",
    latitude: 19.076,
    longitude: 72.8777,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: "203.0.113.1",
    app_version: "1.3.4",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "G",
    social_id: "socialid007",
    first_name: "Rohit",
    last_name: "Singh",
    email: "rohit007@example.com",
    password: "password159",
    country_code: "+44",
    phone: "7700123456",
    dob: new Date("1983-03-30"),
    gender: "male",
    latitude: 51.509865,
    longitude: -0.118092,
    profile_image: null,
    last_login: new Date(),
    login_status: true,
    ip: "198.51.100.0",
    app_version: "2.1.1",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "A",
    social_id: "socialid008",
    first_name: "Pooja",
    last_name: "Kapoor",
    email: "pooja008@example.com",
    password: "password753",
    country_code: null,
    phone: null,
    dob: null,
    gender: "female",
    latitude: null,
    longitude: null,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: null,
    app_version: null,
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "N",
    social_id: "socialid009",
    first_name: "Anil",
    last_name: "Mehta",
    email: "anil009@example.com",
    password: "password852",
    country_code: "+91",
    phone: "1234567890",
    dob: new Date("1979-08-05"),
    gender: "male",
    latitude: 28.6139,
    longitude: 77.209,
    profile_image: "https://example.com/profiles/anil.jpg",
    last_login: null,
    login_status: false,
    ip: "172.16.254.1",
    app_version: "1.0.0",
    is_deleted: false,
    status: "active",
  },
  {
    login_type: "F",
    social_id: "socialid010",
    first_name: "Tina",
    last_name: "Reddy",
    email: "tina010@example.com",
    password: "password456",
    country_code: "+1",
    phone: "5559871234",
    dob: new Date("1996-06-15"),
    gender: "female",
    latitude: 37.7749,
    longitude: -122.4194,
    profile_image: null,
    last_login: null,
    login_status: false,
    ip: null,
    app_version: null,
    is_deleted: false,
    status: "active",
  },
]