// seed.js
import { connect } from 'mongoose';
import Country from './Country.js';
import { env } from '../env.js';

const countriesData = [
 { id: 1, name: 'Afghanistan', nationality: 'Afghan', sortname: 'AF', calling_code: '+93', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 2, name: 'Albania', nationality: 'Albanian', sortname: 'AL', calling_code: '+355', currency_code: 'ALL', currency_name: 'Albanian lek', currency_symbol: 'L', status: 1 },
  { id: 3, name: 'Algeria', nationality: 'Algerian', sortname: 'DZ', calling_code: '+213', currency_code: 'DZD', currency_name: 'Algerian dinar', currency_symbol: 'د.ج', status: 1 },
  { id: 4, name: 'American Samoa', nationality: 'American Samoan', sortname: 'AS', calling_code: '+1684', currency_code: 'USD', currency_name: 'United State Dollar', currency_symbol: '$', status: 1 },
  { id: 5, name: 'Andorra', nationality: 'Andorran', sortname: 'AD', calling_code: '+376', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 6, name: 'Angola', nationality: 'Angolan', sortname: 'AO', calling_code: '+244', currency_code: 'AOA', currency_name: 'Angolan kwanza', currency_symbol: 'Kz', status: 1 },
  { id: 7, name: 'Anguilla', nationality: 'Anguillian', sortname: 'AI', calling_code: '+1264', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 8, name: 'Antarctica', nationality: 'Antarctica', sortname: 'AQ', calling_code: '+672', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 9, name: 'Antigua And Barbuda', nationality: 'Antiguan, Barbudan', sortname: 'AG', calling_code: '+1268', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 10, name: 'Argentina', nationality: 'Argentinean', sortname: 'AR', calling_code: '+54', currency_code: 'ARS', currency_name: 'Argentine peso', currency_symbol: '$', status: 1 },
  { id: 11, name: 'Armenia', nationality: 'Armenian', sortname: 'AM', calling_code: '+374', currency_code: 'AMD', currency_name: 'Armenian dram', currency_symbol: '', status: 1 },
  { id: 12, name: 'Aruba', nationality: 'Aruban', sortname: 'AW', calling_code: '+297', currency_code: 'AWG', currency_name: 'Aruban florin', currency_symbol: 'ƒ', status: 1 },
  { id: 13, name: 'Australia', nationality: 'Australian', sortname: 'AU', calling_code: '+61', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 14, name: 'Austria', nationality: 'Austrian', sortname: 'AT', calling_code: '+43', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 15, name: 'Azerbaijan', nationality: 'Azerbaijani', sortname: 'AZ', calling_code: '994', currency_code: 'AZN', currency_name: 'Azerbaijani manat', currency_symbol: '', status: 1 },
  { id: 16, name: 'Bahamas The', nationality: 'Bahamian', sortname: 'BS', calling_code: '+1', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 17, name: 'Bahrain', nationality: 'Bahraini', sortname: 'BH', calling_code: '+973', currency_code: 'BHD', currency_name: 'Bahraini dinar', currency_symbol: '.د.ب', status: 1 },
  { id: 18, name: 'Bangladesh', nationality: 'Bangladeshi', sortname: 'BD', calling_code: '+880', currency_code: 'BDT', currency_name: 'Bangladeshi taka', currency_symbol: '৳', status: 1 },
  { id: 19, name: 'Barbados', nationality: 'Barbadian', sortname: 'BB', calling_code: '+1246', currency_code: 'BBD', currency_name: 'Barbadian dollar', currency_symbol: '$', status: 1 },
  { id: 20, name: 'Belarus', nationality: 'Belarusian', sortname: 'BY', calling_code: '+375', currency_code: 'BYN', currency_name: 'New Belarusian ruble', currency_symbol: 'Br', status: 1 },
  { id: 21, name: 'Belgium', nationality: 'Belgian', sortname: 'BE', calling_code: '+32', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 22, name: 'Belize', nationality: 'Belizean', sortname: 'BZ', calling_code: '+501', currency_code: 'BZD', currency_name: 'Belize dollar', currency_symbol: '$', status: 1 },
  { id: 23, name: 'Benin', nationality: 'Beninese', sortname: 'BJ', calling_code: '+229', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 24, name: 'Bermuda', nationality: 'Bermudian', sortname: 'BM', calling_code: '+1441', currency_code: 'BMD', currency_name: 'Bermudian dollar', currency_symbol: '$', status: 1 },
  { id: 25, name: 'Bhutan', nationality: 'Bhutanese', sortname: 'BT', calling_code: '+975', currency_code: 'BTN', currency_name: 'Bhutanese ngultrum', currency_symbol: 'Nu.', status: 1 },
  { id: 26, name: 'Bolivia', nationality: 'Bolivian', sortname: 'BO', calling_code: '+591', currency_code: 'BOB', currency_name: 'Bolivian boliviano', currency_symbol: 'Bs.', status: 1 },
  { id: 27, name: 'Bosnia and Herzegovina', nationality: 'Bosnian, Herzegovinian', sortname: 'BA', calling_code: '+387', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 28, name: 'Botswana', nationality: 'Motswana', sortname: 'BW', calling_code: '+267', currency_code: 'BWP', currency_name: 'Botswana pula', currency_symbol: 'P', status: 1 },
  { id: 29, name: 'Bouvet Island', nationality: '', sortname: 'BV', calling_code: '+55', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 30, name: 'Brazil', nationality: 'Brazilian', sortname: 'BR', calling_code: '+55', currency_code: 'BRL', currency_name: 'Brazilian real', currency_symbol: 'R$', status: 1 },
  { id: 31, name: 'British Indian Ocean Territory', nationality: 'Indian', sortname: 'IO', calling_code: '+246', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 32, name: 'Brunei', nationality: 'Bruneian', sortname: 'BN', calling_code: '+673', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 33, name: 'Bulgaria', nationality: 'Bulgarian', sortname: 'BG', calling_code: '+359', currency_code: 'BGN', currency_name: 'Bulgarian lev', currency_symbol: 'лв', status: 1 },
  { id: 34, name: 'Burkina Faso', nationality: 'Burkinabe', sortname: 'BF', calling_code: '+226', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 35, name: 'Burundi', nationality: 'Burundian', sortname: 'BI', calling_code: '+257', currency_code: 'BIF', currency_name: 'Burundian franc', currency_symbol: 'Fr', status: 1 },
  { id: 36, name: 'Cambodia', nationality: 'Cambodian', sortname: 'KH', calling_code: '+855', currency_code: 'KHR', currency_name: 'Cambodian riel', currency_symbol: '៛', status: 1 },
  { id: 37, name: 'Cameroon', nationality: 'Cameroonian', sortname: 'CM', calling_code: '+237', currency_code: 'XAF', currency_name: 'Central African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 38, name: 'Canada', nationality: 'Canadian', sortname: 'CA', calling_code: '+1', currency_code: 'CAD', currency_name: 'Canadian dollar', currency_symbol: '$', status: 1 },
  { id: 39, name: 'Cape Verde', nationality: 'Cape Verdian', sortname: 'CV', calling_code: '+238', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 40, name: 'Cayman Islands', nationality: 'Caymanian', sortname: 'KY', calling_code: '+1345', currency_code: 'KYD', currency_name: 'Cayman Islands dollar', currency_symbol: '$', status: 1 },
  { id: 41, name: 'Central African Republic', nationality: 'Central African', sortname: 'CF', calling_code: '+236', currency_code: 'XAF', currency_name: 'Central African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 42, name: 'Chad', nationality: 'Chadian', sortname: 'TD', calling_code: '+235', currency_code: 'XAF', currency_name: 'Central African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 43, name: 'Chile', nationality: 'Chilean', sortname: 'CL', calling_code: '+56', currency_code: 'CLP', currency_name: 'Chilean peso', currency_symbol: '$', status: 1 },
  { id: 44, name: 'China', nationality: 'Chinese', sortname: 'CN', calling_code: '+86', currency_code: 'CNY', currency_name: 'Chinese yuan', currency_symbol: '¥', status: 1 },
  { id: 45, name: 'Christmas Island', nationality: 'Christmas Island', sortname: 'CX', calling_code: '+61', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 46, name: 'Cocos (Keeling) Islands', nationality: 'Cocos Islander', sortname: 'CC', calling_code: '+61', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 47, name: 'Colombia', nationality: 'Colombian', sortname: 'CO', calling_code: '+57', currency_code: 'COP', currency_name: 'Colombian peso', currency_symbol: '$', status: 1 },
  { id: 48, name: 'Comoros', nationality: 'Comoran', sortname: 'KM', calling_code: '+269', currency_code: 'KMF', currency_name: 'Comorian franc', currency_symbol: 'Fr', status: 1 },
  { id: 49, name: 'Republic Of The Congo', nationality: 'Congolese', sortname: 'CG', calling_code: '+242', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 50, name: 'Democratic Republic Of The Congo', nationality: 'Congolese', sortname: 'CD', calling_code: '+243', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 51, name: 'Cook Islands', nationality: 'Cook Islander', sortname: 'CK', calling_code: '+682', currency_code: 'NZD', currency_name: 'New Zealand dollar', currency_symbol: '$', status: 1 },
  { id: 52, name: 'Costa Rica', nationality: 'Costa Rican', sortname: 'CR', calling_code: '+506', currency_code: 'CRC', currency_name: 'Costa Rican colón', currency_symbol: '₡', status: 1 },
  { id: 53, name: 'Cote D\'Ivoire (Ivory Coast)', nationality: 'Ivorian', sortname: 'CI', calling_code: '+225', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 54, name: 'Croatia (Hrvatska)', nationality: 'Croatian', sortname: 'HR', calling_code: '+385', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 55, name: 'Cuba', nationality: 'Cuban', sortname: 'CU', calling_code: '+53', currency_code: 'CUC', currency_name: 'Cuban convertible peso', currency_symbol: '$', status: 1 },
  { id: 56, name: 'Cyprus', nationality: 'Cypriot', sortname: 'CY', calling_code: '+357', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 57, name: 'Czech Republic', nationality: 'Czech', sortname: 'CZ', calling_code: '+420', currency_code: 'CZK', currency_name: 'Czech koruna', currency_symbol: 'Kč', status: 1 },
  { id: 58, name: 'Denmark', nationality: 'Danish', sortname: 'DK', calling_code: '+45', currency_code: 'DKK', currency_name: 'Danish krone', currency_symbol: 'kr', status: 1 },
  { id: 59, name: 'Djibouti', nationality: 'Djibouti', sortname: 'DJ', calling_code: '+253', currency_code: 'DJF', currency_name: 'Djiboutian franc', currency_symbol: 'Fr', status: 1 },
  { id: 60, name: 'Dominica', nationality: 'Dominican', sortname: 'DM', calling_code: '+1767', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 61, name: 'Dominican Republic', nationality: 'Dominican', sortname: 'DO', calling_code: '+1809', currency_code: 'DOP', currency_name: 'Dominican peso', currency_symbol: '$', status: 1 },
  { id: 62, name: 'East Timor', nationality: 'Zimbabwean', sortname: 'TP', calling_code: '+670', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 63, name: 'Ecuador', nationality: 'Ecuadorean', sortname: 'EC', calling_code: '+593', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 64, name: 'Egypt', nationality: 'Egyptian', sortname: 'EG', calling_code: '+20', currency_code: 'EGP', currency_name: 'Egyptian pound', currency_symbol: '£', status: 1 },
  { id: 65, name: 'El Salvador', nationality: 'Salvadoran', sortname: 'SV', calling_code: '+503', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 66, name: 'Equatorial Guinea', nationality: 'Equatorial Guinean', sortname: 'GQ', calling_code: '+240', currency_code: 'XAF', currency_name: 'Central African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 67, name: 'Eritrea', nationality: 'Eritrean', sortname: 'ER', calling_code: '+291', currency_code: 'ERN', currency_name: 'Eritrean nakfa', currency_symbol: 'Nfk', status: 1 },
  { id: 68, name: 'Estonia', nationality: 'Estonian', sortname: 'EE', calling_code: '+372', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 69, name: 'Ethiopia', nationality: 'Ethiopian', sortname: 'ET', calling_code: '+251', currency_code: 'ETB', currency_name: 'Ethiopian birr', currency_symbol: 'Br', status: 1 },
  { id: 70, name: 'External Territories of Australia', nationality: 'Zimbabwean', sortname: 'XA', calling_code: '+672', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 71, name: 'Falkland Islands', nationality: 'Falkland Islander', sortname: 'FK', calling_code: '+500', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 72, name: 'Faroe Islands', nationality: 'Faroese', sortname: 'FO', calling_code: '+298', currency_code: 'DKK', currency_name: 'Danish krone', currency_symbol: 'kr', status: 1 },
  { id: 73, name: 'Fiji Islands', nationality: 'Fijian', sortname: 'FJ', calling_code: '+679', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 74, name: 'Finland', nationality: 'Finnish', sortname: 'FI', calling_code: '+358', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 75, name: 'France', nationality: 'French', sortname: 'FR', calling_code: '+33', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 76, name: 'French Guiana', nationality: '', sortname: 'GF', calling_code: '+594', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 77, name: 'French Polynesia', nationality: 'French Polynesian', sortname: 'PF', calling_code: '+689', currency_code: 'XPF', currency_name: 'CFP franc', currency_symbol: 'Fr', status: 1 },
  { id: 78, name: 'French Southern Territories', nationality: 'French', sortname: 'TF', calling_code: '+262', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 79, name: 'Gabon', nationality: 'Gabonese', sortname: 'GA', calling_code: '+241', currency_code: 'XAF', currency_name: 'Central African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 80, name: 'Gambia The', nationality: 'Gambian', sortname: 'GM', calling_code: '+220', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 81, name: 'Georgia', nationality: 'Georgian', sortname: 'GE', calling_code: '+995', currency_code: 'GEL', currency_name: 'Georgian Lari', currency_symbol: 'ლ', status: 1 },
  { id: 82, name: 'Germany', nationality: 'German', sortname: 'DE', calling_code: '+49', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 83, name: 'Ghana', nationality: 'Ghanaian', sortname: 'GH', calling_code: '+233', currency_code: 'GHS', currency_name: 'Ghanaian cedi', currency_symbol: '₵', status: 1 },
  { id: 84, name: 'Gibraltar', nationality: 'Gibraltar', sortname: 'GI', calling_code: '+350', currency_code: 'GIP', currency_name: 'Gibraltar pound', currency_symbol: '£', status: 1 },
  { id: 85, name: 'Greece', nationality: 'Greek', sortname: 'GR', calling_code: '+30', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 86, name: 'Greenland', nationality: 'Greenlandic', sortname: 'GL', calling_code: '+299', currency_code: 'DKK', currency_name: 'Danish krone', currency_symbol: 'kr', status: 1 },
  { id: 87, name: 'Grenada', nationality: 'Grenadian', sortname: 'GD', calling_code: '+1473', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 88, name: 'Guadeloupe', nationality: 'Guadeloupian', sortname: 'GP', calling_code: '+590', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 89, name: 'Guam', nationality: 'Guamanian', sortname: 'GU', calling_code: '+1671', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 90, name: 'Guatemala', nationality: 'Guatemalan', sortname: 'GT', calling_code: '+502', currency_code: 'GTQ', currency_name: 'Guatemalan quetzal', currency_symbol: 'Q', status: 1 },
  { id: 91, name: 'Guernsey and Alderney', nationality: 'Zimbabwean', sortname: 'XU', calling_code: '+44-1481', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 92, name: 'Guinea', nationality: 'Guinean', sortname: 'GN', calling_code: '+224', currency_code: 'GNF', currency_name: 'Guinean franc', currency_symbol: 'Fr', status: 1 },
  { id: 93, name: 'Guinea-Bissau', nationality: 'Guinea-Bissauan', sortname: 'GW', calling_code: '+245', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 94, name: 'Guyana', nationality: 'Guyanese', sortname: 'GY', calling_code: '+592', currency_code: 'GYD', currency_name: 'Guyanese dollar', currency_symbol: '$', status: 1 },
  { id: 95, name: 'Haiti', nationality: 'Haitian', sortname: 'HT', calling_code: '+509', currency_code: 'HTG', currency_name: 'Haitian gourde', currency_symbol: 'G', status: 1 },
  { id: 96, name: 'Heard and McDonald Islands', nationality: 'Heard and McDonald Islander', sortname: 'HM', calling_code: '+0', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 97, name: 'Honduras', nationality: 'Honduran', sortname: 'HN', calling_code: '+504', currency_code: 'HNL', currency_name: 'Honduran lempira', currency_symbol: 'L', status: 1 },
  { id: 98, name: 'Hong Kong S.A.R.', nationality: 'Chinese', sortname: 'HK', calling_code: '+852', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 99, name: 'Hungary', nationality: 'Hungarian', sortname: 'HU', calling_code: '+36', currency_code: 'HUF', currency_name: 'Hungarian forint', currency_symbol: 'Ft', status: 1 },
  { id: 100, name: 'Iceland', nationality: 'Icelander', sortname: 'IS', calling_code: '+354', currency_code: 'ISK', currency_name: 'Icelandic króna', currency_symbol: 'kr', status: 1 },
  { id: 101, name: 'India', nationality: 'Indian', sortname: 'IN', calling_code: '+91', currency_code: 'INR', currency_name: 'Indian rupee', currency_symbol: '₹', status: 1 },
  { id: 102, name: 'Indonesia', nationality: 'Indonesian', sortname: 'ID', calling_code: '+62', currency_code: 'IDR', currency_name: 'Indonesian rupiah', currency_symbol: 'Rp', status: 1 },
  { id: 103, name: 'Iran', nationality: 'Iranian', sortname: 'IR', calling_code: '+98', currency_code: 'IRR', currency_name: 'Iranian rial', currency_symbol: '﷼', status: 1 },
  { id: 104, name: 'Iraq', nationality: 'Iraqi', sortname: 'IQ', calling_code: '+964', currency_code: 'IQD', currency_name: 'Iraqi dinar', currency_symbol: 'ع.د', status: 1 },
  { id: 105, name: 'Ireland', nationality: 'Irish', sortname: 'IE', calling_code: '+353', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 106, name: 'Israel', nationality: 'Israeli', sortname: 'IL', calling_code: '+972', currency_code: 'ILS', currency_name: 'Israeli new shekel', currency_symbol: '₪', status: 1 },
  { id: 107, name: 'Italy', nationality: 'Italian', sortname: 'IT', calling_code: '+39', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 108, name: 'Jamaica', nationality: 'Jamaican', sortname: 'JM', calling_code: '+1876', currency_code: 'JMD', currency_name: 'Jamaican dollar', currency_symbol: '$', status: 1 },
  { id: 109, name: 'Japan', nationality: 'Japanese', sortname: 'JP', calling_code: '+81', currency_code: 'JPY', currency_name: 'Japanese yen', currency_symbol: '¥', status: 1 },
  { id: 110, name: 'Jersey', nationality: 'Zimbabwean', sortname: 'XJ', calling_code: '+44', currency_code: 'GBP', currency_name: 'British pound', currency_symbol: '£', status: 1 },
  { id: 111, name: 'Jordan', nationality: 'Jordanian', sortname: 'JO', calling_code: '+962', currency_code: 'JOD', currency_name: 'Jordanian dinar', currency_symbol: 'د.ا', status: 1 },
  { id: 112, name: 'Kazakhstan', nationality: 'Kazakhstani', sortname: 'KZ', calling_code: '+7', currency_code: 'KZT', currency_name: 'Kazakhstani tenge', currency_symbol: '', status: 1 },
  { id: 113, name: 'Kenya', nationality: 'Kenyan', sortname: 'KE', calling_code: '+254', currency_code: 'KES', currency_name: 'Kenyan shilling', currency_symbol: 'Sh', status: 1 },
  { id: 114, name: 'Kiribati', nationality: 'I-Kiribati', sortname: 'KI', calling_code: '+686', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 115, name: 'Korea North', nationality: 'North Korean', sortname: 'KP', calling_code: '+850', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 116, name: 'South Korean', nationality: 'South Korean', sortname: 'KR', calling_code: '+82', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 117, name: 'Kuwait', nationality: 'Kuwaiti', sortname: 'KW', calling_code: '+965', currency_code: 'KWD', currency_name: 'Kuwaiti dinar', currency_symbol: 'د.ك', status: 1 },
  { id: 118, name: 'Kyrgyzstan', nationality: 'Kirghiz', sortname: 'KG', calling_code: '+996', currency_code: 'KGS', currency_name: 'Kyrgyzstani som', currency_symbol: 'с', status: 1 },
  { id: 119, name: 'Laos', nationality: 'Laotian', sortname: 'LA', calling_code: '+856', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 120, name: 'Latvia', nationality: 'Latvian', sortname: 'LV', calling_code: '+371', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 121, name: 'Lebanon', nationality: 'Lebanese', sortname: 'LB', calling_code: '+961', currency_code: 'LBP', currency_name: 'Lebanese pound', currency_symbol: 'ل.ل', status: 1 },
  { id: 122, name: 'Lesotho', nationality: 'Mosotho', sortname: 'LS', calling_code: '+266', currency_code: 'LSL', currency_name: 'Lesotho loti', currency_symbol: 'L', status: 1 },
  { id: 123, name: 'Liberia', nationality: 'Liberian', sortname: 'LR', calling_code: '+231', currency_code: 'LRD', currency_name: 'Liberian dollar', currency_symbol: '$', status: 1 },
  { id: 124, name: 'Libya', nationality: 'Libyan', sortname: 'LY', calling_code: '+218', currency_code: 'LYD', currency_name: 'Libyan dinar', currency_symbol: 'ل.د', status: 1 },
  { id: 125, name: 'Liechtenstein', nationality: 'Liechtensteiner', sortname: 'LI', calling_code: '+423', currency_code: 'CHF', currency_name: 'Swiss franc', currency_symbol: 'Fr', status: 1 },
  { id: 126, name: 'Lithuania', nationality: 'Lithuanian', sortname: 'LT', calling_code: '+370', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 127, name: 'Luxembourg', nationality: 'Luxembourger', sortname: 'LU', calling_code: '+352', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 128, name: 'Macau S.A.R.', nationality: 'Chinese', sortname: 'MO', calling_code: '+853', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 129, name: 'Macedonia', nationality: 'Macedonian', sortname: 'MK', calling_code: '+389', currency_code: 'MKD', currency_name: 'Macedonian denar', currency_symbol: 'ден', status: 1 },
  { id: 130, name: 'Madagascar', nationality: 'Malagasy', sortname: 'MG', calling_code: '+261', currency_code: 'MGA', currency_name: 'Malagasy ariary', currency_symbol: 'Ar', status: 1 },
  { id: 131, name: 'Malawi', nationality: 'Malawian', sortname: 'MW', calling_code: '+265', currency_code: 'MWK', currency_name: 'Malawian kwacha', currency_symbol: 'MK', status: 1 },
  { id: 132, name: 'Malaysia', nationality: 'Malaysian', sortname: 'MY', calling_code: '+60', currency_code: 'MYR', currency_name: 'Malaysian ringgit', currency_symbol: 'RM', status: 1 },
  { id: 133, name: 'Maldives', nationality: 'Maldivan', sortname: 'MV', calling_code: '+960', currency_code: 'MVR', currency_name: 'Maldivian rufiyaa', currency_symbol: '.ރ', status: 1 },
  { id: 134, name: 'Mali', nationality: 'Malian', sortname: 'ML', calling_code: '+223', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 135, name: 'Malta', nationality: 'Maltese', sortname: 'MT', calling_code: '+356', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 136, name: 'Man (Isle of)', nationality: 'Zimbabwean', sortname: 'XM', calling_code: '+44', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 137, name: 'Marshall Islands', nationality: 'Marshallese', sortname: 'MH', calling_code: '+692', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 138, name: 'Martinique', nationality: 'French', sortname: 'MQ', calling_code: '+596', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 139, name: 'Mauritania', nationality: 'Mauritanian', sortname: 'MR', calling_code: '+222', currency_code: 'MRO', currency_name: 'Mauritanian ouguiya', currency_symbol: 'UM', status: 1 },
  { id: 140, name: 'Mauritius', nationality: 'Mauritian', sortname: 'MU', calling_code: '+230', currency_code: 'MUR', currency_name: 'Mauritian rupee', currency_symbol: '₨', status: 1 },
  { id: 141, name: 'Mayotte', nationality: 'French', sortname: 'YT', calling_code: '+262', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 142, name: 'Mexico', nationality: 'Mexican', sortname: 'MX', calling_code: '+52', currency_code: 'MXN', currency_name: 'Mexican peso', currency_symbol: '$', status: 1 },
  { id: 143, name: 'Micronesia', nationality: 'Micronesian', sortname: 'FM', calling_code: '+691', currency_code: '', currency_name: '[D]', currency_symbol: '$', status: 1 },
  { id: 144, name: 'Moldova', nationality: 'Moldovan', sortname: 'MD', calling_code: '+373', currency_code: 'MDL', currency_name: 'Moldovan leu', currency_symbol: 'L', status: 1 },
  { id: 145, name: 'Monaco', nationality: 'Monegasque', sortname: 'MC', calling_code: '+377', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 146, name: 'Mongolia', nationality: 'Mongolian', sortname: 'MN', calling_code: '+976', currency_code: 'MNT', currency_name: 'Mongolian tögrög', currency_symbol: '₮', status: 1 },
  { id: 147, name: 'Montserrat', nationality: 'Montserratian', sortname: 'MS', calling_code: '+1664', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 148, name: 'Morocco', nationality: 'Moroccan', sortname: 'MA', calling_code: '+212', currency_code: 'MAD', currency_name: 'Moroccan dirham', currency_symbol: 'د.م.', status: 1 },
  { id: 149, name: 'Mozambique', nationality: 'Mozambican', sortname: 'MZ', calling_code: '+258', currency_code: 'MZN', currency_name: 'Mozambican metical', currency_symbol: 'MT', status: 1 },
  { id: 150, name: 'Myanmar', nationality: 'Burmese', sortname: 'MM', calling_code: '+95', currency_code: 'MMK', currency_name: 'Burmese kyat', currency_symbol: 'Ks', status: 1 },
  { id: 151, name: 'Namibia', nationality: 'Namibian', sortname: 'NA', calling_code: '+264', currency_code: 'NAD', currency_name: 'Namibian dollar', currency_symbol: '$', status: 1 },
  { id: 152, name: 'Nauru', nationality: 'Nauruan', sortname: 'NR', calling_code: '+674', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 153, name: 'Nepal', nationality: 'Nepalese', sortname: 'NP', calling_code: '+977', currency_code: 'NPR', currency_name: 'Nepalese rupee', currency_symbol: '₨', status: 1 },
  { id: 154, name: 'Netherlands Antilles', nationality: 'Zimbabwean', sortname: 'AN', calling_code: '+599', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 155, name: 'Netherlands The', nationality: 'Dutch', sortname: 'NL', calling_code: '+31', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 156, name: 'New Caledonia', nationality: 'New Caledonian', sortname: 'NC', calling_code: '+687', currency_code: 'XPF', currency_name: 'CFP franc', currency_symbol: 'Fr', status: 1 },
  { id: 157, name: 'New Zealand', nationality: 'New Zealander', sortname: 'NZ', calling_code: '+64', currency_code: 'NZD', currency_name: 'New Zealand dollar', currency_symbol: '$', status: 1 },
  { id: 158, name: 'Nicaragua', nationality: 'Nicaraguan', sortname: 'NI', calling_code: '+505', currency_code: 'NIO', currency_name: 'Nicaraguan córdoba', currency_symbol: 'C$', status: 1 },
  { id: 159, name: 'Niger', nationality: 'Nigerien', sortname: 'NE', calling_code: '+227', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 160, name: 'Nigeria', nationality: 'Nigerian', sortname: 'NG', calling_code: '+234', currency_code: 'NGN', currency_name: 'Nigerian naira', currency_symbol: '₦', status: 1 },
  { id: 161, name: 'Niue', nationality: 'Niuean', sortname: 'NU', calling_code: '+683', currency_code: 'NZD', currency_name: 'New Zealand dollar', currency_symbol: '$', status: 1 },
  { id: 162, name: 'Norfolk Island', nationality: 'Norfolk Islander', sortname: 'NF', calling_code: '+672', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 163, name: 'Northern Mariana Islands', nationality: 'American', sortname: 'MP', calling_code: '+1670', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 164, name: 'Norway', nationality: 'Norwegian', sortname: 'NO', calling_code: '+47', currency_code: 'NOK', currency_name: 'Norwegian krone', currency_symbol: 'kr', status: 1 },
  { id: 165, name: 'Oman', nationality: 'Omani', sortname: 'OM', calling_code: '+968', currency_code: 'OMR', currency_name: 'Omani rial', currency_symbol: 'ر.ع.', status: 1 },
  { id: 166, name: 'Pakistan', nationality: 'Pakistani', sortname: 'PK', calling_code: '+92', currency_code: 'PKR', currency_name: 'Pakistani rupee', currency_symbol: '₨', status: 1 },
  { id: 167, name: 'Palau', nationality: 'Palauan', sortname: 'PW', calling_code: '+680', currency_code: '(none)', currency_name: '[E]', currency_symbol: '$', status: 1 },
  { id: 168, name: 'Palestinian Territory Occupied', nationality: 'Palestinian', sortname: 'PS', calling_code: '+970', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 169, name: 'Panama', nationality: 'Panamanian', sortname: 'PA', calling_code: '+507', currency_code: 'PAB', currency_name: 'Panamanian balboa', currency_symbol: 'B/.', status: 1 },
  { id: 170, name: 'Papua new Guinea', nationality: 'Papua New Guinean', sortname: 'PG', calling_code: '+675', currency_code: 'PGK', currency_name: 'Papua New Guinean kina', currency_symbol: 'K', status: 1 },
  { id: 171, name: 'Paraguay', nationality: 'Paraguayan', sortname: 'PY', calling_code: '+595', currency_code: 'PYG', currency_name: 'Paraguayan guaraní', currency_symbol: '₲', status: 1 },
  { id: 172, name: 'Peru', nationality: 'Peruvian', sortname: 'PE', calling_code: '+51', currency_code: 'PEN', currency_name: 'Peruvian sol', currency_symbol: 'S/.', status: 1 },
  { id: 173, name: 'Philippines', nationality: 'Filipino', sortname: 'PH', calling_code: '+63', currency_code: 'PHP', currency_name: 'Philippine peso', currency_symbol: '₱', status: 1 },
  { id: 174, name: 'Pitcairn Island', nationality: 'Pitcairn Islander', sortname: 'PN', calling_code: '+64', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 175, name: 'Poland', nationality: 'Polish', sortname: 'PL', calling_code: '+48', currency_code: 'PLN', currency_name: 'Polish złoty', currency_symbol: 'zł', status: 1 },
  { id: 176, name: 'Portugal', nationality: 'Portuguese', sortname: 'PT', calling_code: '+351', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 177, name: 'Puerto Rico', nationality: 'Puerto Rican', sortname: 'PR', calling_code: '+1787', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 178, name: 'Qatar', nationality: 'Qatari', sortname: 'QA', calling_code: '+974', currency_code: 'QAR', currency_name: 'Qatari riyal', currency_symbol: 'ر.ق', status: 1 },
  { id: 179, name: 'Reunion', nationality: 'French', sortname: 'RE', calling_code: '+262', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 180, name: 'Romania', nationality: 'Romanian', sortname: 'RO', calling_code: '+40', currency_code: 'RON', currency_name: 'Romanian leu', currency_symbol: 'lei', status: 1 },
  { id: 181, name: 'Russia', nationality: 'Russian', sortname: 'RU', calling_code: '+7', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 182, name: 'Rwanda', nationality: 'Rwandan', sortname: 'RW', calling_code: '+250', currency_code: 'RWF', currency_name: 'Rwandan franc', currency_symbol: 'Fr', status: 1 },
  { id: 183, name: 'Saint Helena', nationality: 'Saint Helenian', sortname: 'SH', calling_code: '+290', currency_code: 'SHP', currency_name: 'Saint Helena pound', currency_symbol: '£', status: 1 },
  { id: 184, name: 'Saint Kitts And Nevis', nationality: 'Kittian and Nevisian', sortname: 'KN', calling_code: '+1869', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 185, name: 'Saint Lucia', nationality: 'Saint Lucian', sortname: 'LC', calling_code: '+1758', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 186, name: 'Saint Pierre and Miquelon', nationality: 'French', sortname: 'PM', calling_code: '+508', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 187, name: 'Saint Vincent And The Grenadines', nationality: 'Saint Vincentian', sortname: 'VC', calling_code: '+1784', currency_code: 'XCD', currency_name: 'East Caribbean dollar', currency_symbol: '$', status: 1 },
  { id: 188, name: 'Samoa', nationality: 'Samoan', sortname: 'WS', calling_code: '+685', currency_code: 'WST', currency_name: 'Samoan tālā', currency_symbol: 'T', status: 1 },
  { id: 189, name: 'San Marino', nationality: 'Sammarinese', sortname: 'SM', calling_code: '+378', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 190, name: 'Sao Tome and Principe', nationality: 'Sao Tomean', sortname: 'ST', calling_code: '+239', currency_code: 'STD', currency_name: 'São Tomé and Príncipe dobra', currency_symbol: 'Db', status: 1 },
  { id: 191, name: 'Saudi Arabia', nationality: 'Saudi Arabian', sortname: 'SA', calling_code: '+966', currency_code: 'SAR', currency_name: 'Saudi riyal', currency_symbol: 'ر.س', status: 1 },
  { id: 192, name: 'Senegal', nationality: 'Senegalese', sortname: 'SN', calling_code: '+221', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 193, name: 'Serbia', nationality: 'Serbian', sortname: 'RS', calling_code: '+381', currency_code: 'RSD', currency_name: 'Serbian dinar', currency_symbol: 'дин.', status: 1 },
  { id: 194, name: 'Seychelles', nationality: 'Seychellois', sortname: 'SC', calling_code: '+248', currency_code: 'SCR', currency_name: 'Seychellois rupee', currency_symbol: '₨', status: 1 },
  { id: 195, name: 'Sierra Leone', nationality: 'Sierra Leonean', sortname: 'SL', calling_code: '+232', currency_code: 'SLL', currency_name: 'Sierra Leonean leone', currency_symbol: 'Le', status: 1 },
  { id: 196, name: 'Singapore', nationality: 'Singaporean', sortname: 'SG', calling_code: '+65', currency_code: 'BND', currency_name: 'Brunei dollar', currency_symbol: '$', status: 1 },
  { id: 197, name: 'Slovakia', nationality: 'Slovak', sortname: 'SK', calling_code: '+421', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 198, name: 'Slovenia', nationality: 'Slovene', sortname: 'SI', calling_code: '+386', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 199, name: 'Smaller Territories of the UK', nationality: 'Zimbabwean', sortname: 'XG', calling_code: '+44', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 200, name: 'Solomon Islands', nationality: 'Solomon Islander', sortname: 'SB', calling_code: '+677', currency_code: 'SBD', currency_name: 'Solomon Islands dollar', currency_symbol: '$', status: 1 },
  { id: 201, name: 'Somalia', nationality: 'Somali', sortname: 'SO', calling_code: '+252', currency_code: 'SOS', currency_name: 'Somali shilling', currency_symbol: 'Sh', status: 1 },
  { id: 202, name: 'South Africa', nationality: 'South African', sortname: 'ZA', calling_code: '+27', currency_code: 'ZAR', currency_name: 'South African rand', currency_symbol: 'R', status: 1 },
  { id: 203, name: 'South Georgia', nationality: 'South Georgia and the South Sandwich Islander', sortname: 'GS', calling_code: '+500', currency_code: 'GBP', currency_name: 'British pound', currency_symbol: '£', status: 1 },
  { id: 204, name: 'South Sudan', nationality: 'South Sudanese', sortname: 'SS', calling_code: '+211', currency_code: 'SSP', currency_name: 'South Sudanese pound', currency_symbol: '£', status: 1 },
  { id: 205, name: 'Spain', nationality: 'Spanish', sortname: 'ES', calling_code: '+34', currency_code: 'EUR', currency_name: 'Euro', currency_symbol: '€', status: 1 },
  { id: 206, name: 'Sri Lanka', nationality: 'Sri Lankan', sortname: 'LK', calling_code: '+94', currency_code: 'LKR', currency_name: 'Sri Lankan rupee', currency_symbol: 'Rs', status: 1 },
  { id: 207, name: 'Sudan', nationality: 'Sudanese', sortname: 'SD', calling_code: '+249', currency_code: 'SDG', currency_name: 'Sudanese pound', currency_symbol: 'ج.س.', status: 1 },
  { id: 208, name: 'Suriname', nationality: 'Surinamer', sortname: 'SR', calling_code: '+597', currency_code: 'SRD', currency_name: 'Surinamese dollar', currency_symbol: '$', status: 1 },
  { id: 209, name: 'Svalbard And Jan Mayen Islands', nationality: 'Norwegian', sortname: 'SJ', calling_code: '+47', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 210, name: 'Swaziland', nationality: 'Swazi', sortname: 'SZ', calling_code: '+268', currency_code: 'SZL', currency_name: 'Swazi lilangeni', currency_symbol: 'L', status: 1 },
  { id: 211, name: 'Sweden', nationality: 'Swedish', sortname: 'SE', calling_code: '+46', currency_code: 'SEK', currency_name: 'Swedish krona', currency_symbol: 'kr', status: 1 },
  { id: 212, name: 'Switzerland', nationality: 'Swiss', sortname: 'CH', calling_code: '+41', currency_code: 'CHF', currency_name: 'Swiss franc', currency_symbol: 'Fr', status: 1 },
  { id: 213, name: 'Syria', nationality: 'Syrian', sortname: 'SY', calling_code: '+963', currency_code: 'SYP', currency_name: 'Syrian pound', currency_symbol: '£', status: 1 },
  { id: 214, name: 'Taiwan', nationality: 'Taiwanese', sortname: 'TW', calling_code: '+886', currency_code: 'TWD', currency_name: 'New Taiwan dollar', currency_symbol: '$', status: 1 },
  { id: 215, name: 'Tajikistan', nationality: 'Tadzhik', sortname: 'TJ', calling_code: '+992', currency_code: 'TJS', currency_name: 'Tajikistani somoni', currency_symbol: 'ЅМ', status: 1 },
  { id: 216, name: 'Tanzania', nationality: 'Tanzanian', sortname: 'TZ', calling_code: '+255', currency_code: 'TZS', currency_name: 'Tanzanian shilling', currency_symbol: 'Sh', status: 1 },
  { id: 217, name: 'Thailand', nationality: 'Thai', sortname: 'TH', calling_code: '+66', currency_code: 'THB', currency_name: 'Thai baht', currency_symbol: '฿', status: 1 },
  { id: 218, name: 'Togo', nationality: 'Togolese', sortname: 'TG', calling_code: '+228', currency_code: 'XOF', currency_name: 'West African CFA franc', currency_symbol: 'Fr', status: 1 },
  { id: 219, name: 'Tokelau', nationality: 'Tokelauan', sortname: 'TK', calling_code: '+690', currency_code: 'NZD', currency_name: 'New Zealand dollar', currency_symbol: '$', status: 1 },
  { id: 220, name: 'Tonga', nationality: 'Tongan', sortname: 'TO', calling_code: '+676', currency_code: 'TOP', currency_name: 'Tongan paʻanga', currency_symbol: 'T$', status: 1 },
  { id: 221, name: 'Trinidad And Tobago', nationality: 'Trinidadian', sortname: 'TT', calling_code: '+1868', currency_code: 'TTD', currency_name: 'Trinidad and Tobago dollar', currency_symbol: '$', status: 1 },
  { id: 222, name: 'Tunisia', nationality: 'Tunisian', sortname: 'TN', calling_code: '+216', currency_code: 'TND', currency_name: 'Tunisian dinar', currency_symbol: 'د.ت', status: 1 },
  { id: 223, name: 'Turkey', nationality: 'Turkish', sortname: 'TR', calling_code: '+90', currency_code: 'TRY', currency_name: 'Turkish lira', currency_symbol: '', status: 1 },
  { id: 224, name: 'Turkmenistan', nationality: 'Turkmen', sortname: 'TM', calling_code: '+993', currency_code: 'TMT', currency_name: 'Turkmenistan manat', currency_symbol: 'm', status: 1 },
  { id: 225, name: 'Turks And Caicos Islands', nationality: 'Turks and Caicos Islander', sortname: 'TC', calling_code: '+1649', currency_code: 'USD', currency_name: 'United States dollar', currency_symbol: '$', status: 1 },
  { id: 226, name: 'Tuvalu', nationality: 'Tuvaluan', sortname: 'TV', calling_code: '+688', currency_code: 'AUD', currency_name: 'Australian dollar', currency_symbol: '$', status: 1 },
  { id: 227, name: 'Uganda', nationality: 'Ugandan', sortname: 'UG', calling_code: '+256', currency_code: 'UGX', currency_name: 'Ugandan shilling', currency_symbol: 'Sh', status: 1 },
  { id: 228, name: 'Ukraine', nationality: 'Ukrainian', sortname: 'UA', calling_code: '+380', currency_code: 'UAH', currency_name: 'Ukrainian hryvnia', currency_symbol: '₴', status: 1 },
  { id: 229, name: 'United Arab Emirates', nationality: 'Emirati', sortname: 'AE', calling_code: '+971', currency_code: 'AED', currency_name: 'United Arab Emirates dirham', currency_symbol: 'د.إ', status: 1 },
  { id: 230, name: 'United Kingdom', nationality: 'British', sortname: 'GB', calling_code: '+44', currency_code: 'GBP', currency_name: 'British pound', currency_symbol: '£', status: 1 },
  { id: 231, name: 'United States', nationality: 'American', sortname: 'US', calling_code: '+1', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 232, name: 'United States Minor Outlying Islands', nationality: 'American', sortname: 'UM', calling_code: '', currency_code: 'USD', currency_name: 'United States Dollar', currency_symbol: '$', status: 1 },
  { id: 233, name: 'Uruguay', nationality: 'Uruguayan', sortname: 'UY', calling_code: '+598', currency_code: 'UYU', currency_name: 'Uruguayan peso', currency_symbol: '$', status: 1 },
  { id: 234, name: 'Uzbekistan', nationality: 'Uzbekistani', sortname: 'UZ', calling_code: '+998', currency_code: 'UZS', currency_name: 'Uzbekistani so\'m', currency_symbol: '', status: 1 },
  { id: 235, name: 'Vanuatu', nationality: 'Ni-Vanuatu', sortname: 'VU', calling_code: '+678', currency_code: 'VUV', currency_name: 'Vanuatu vatu', currency_symbol: 'Vt', status: 1 },
  { id: 236, name: 'Vatican City State (Holy See)', nationality: '', sortname: 'VA', calling_code: '+379', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 237, name: 'Venezuela', nationality: 'Venezuelan', sortname: 'VE', calling_code: '+58', currency_code: 'VEF', currency_name: 'Venezuelan bolívar', currency_symbol: 'Bs F', status: 1 },
  { id: 238, name: 'Vietnam', nationality: 'Vietnamese', sortname: 'VN', calling_code: '84', currency_code: 'VND', currency_name: 'Vietnamese đồng', currency_symbol: '₫', status: 1 },
  { id: 239, name: 'Virgin Islands (British)', nationality: 'Virgin Islander', sortname: 'VG', calling_code: '+1284', currency_code: '', currency_name: '[D]', currency_symbol: '$', status: 1 },
  { id: 240, name: 'Virgin Islands (US)', nationality: 'Virgin Islander', sortname: 'VI', calling_code: '+340', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 241, name: 'Wallis And Futuna Islands', nationality: 'Wallis and Futuna Islander', sortname: 'WF', calling_code: '+681', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 242, name: 'Western Sahara', nationality: 'Sahrawi', sortname: 'EH', calling_code: '+212', currency_code: 'MAD', currency_name: 'Moroccan dirham', currency_symbol: 'د.م.', status: 1 },
  { id: 243, name: 'Yemen', nationality: 'Yemeni', sortname: 'YE', calling_code: '+967', currency_code: 'YER', currency_name: 'Yemeni rial', currency_symbol: '﷼', status: 1 },
  { id: 244, name: 'Yugoslavia', nationality: 'Zimbabwean', sortname: 'YU', calling_code: '+38', currency_code: '', currency_name: '', currency_symbol: '', status: 1 },
  { id: 245, name: 'Zambia', nationality: 'Zambian', sortname: 'ZM', calling_code: '+260', currency_code: 'ZMW', currency_name: 'Zambian kwacha', currency_symbol: 'ZK', status: 1 },
  { id: 246, name: 'Zimbabwe', nationality: 'Zimbabwean', sortname: 'ZW', calling_code: '+263', currency_code: 'BWP', currency_name: 'Botswana pula', currency_symbol: 'P', status: 1 }
];

// Connection URI example (change for your MongoDB)
const MONGO_URI = env.DATABASE_URI;

async function seedCountries() {
  try {
    await connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    console.log('Connected to MongoDB');

    // Optional: clear current collections
    await Country.deleteMany({});
    console.log('Old countries data cleared');

    // Bulk insert
    await Country.insertMany(countriesData);
    console.log('Countries data seeded successfully');

    process.exit(0);
  } catch (err) {
    console.error('Error seeding country data:', err);
    process.exit(1);
  }
}

seedCountries();
